# Generated by Django 4.2.13 on 2024-07-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='numero_test',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
