# Generated by Django 4.2.13 on 2024-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiteur', '0003_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='heure_sortie',
            field=models.DateTimeField(blank=True),
        ),
    ]
