# Generated by Django 4.2.13 on 2024-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiteur', '0004_alter_visite_heure_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='heure_sortie',
            field=models.DateTimeField(null=True),
        ),
    ]
