# Generated by Django 4.2.13 on 2024-08-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiteur', '0005_alter_visite_heure_sortie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visite',
            old_name='id_visiteur',
            new_name='visiteur',
        ),
    ]
