# Generated by Django 4.2.13 on 2024-09-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visiteur', '0006_rename_id_visiteur_visite_visiteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='visiteur',
            name='role_visiteur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='visite',
            name='service_visite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visiteur.service'),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='mon_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visiteur.service'),
        ),
    ]
